In [1]:
!pip install xgboost lightgbm catboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.4.6)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.3.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer

from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier, 
                              ExtraTreesClassifier, HistGradientBoostingClassifier, 
                              BaggingClassifier, AdaBoostClassifier)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [3]:
df_train = pd.read_csv('/kaggle/input/competitions/spaceship-titanic/train.csv')
df_test = pd.read_csv('/kaggle/input/competitions/spaceship-titanic/test.csv')

In [4]:
df_train = df_train.set_index(['PassengerId'])
df_test = df_test.set_index(['PassengerId'])

In [5]:
df_train.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
PassengerId,,,,,,,,,,,,,
0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8693 entries, 0001_01 to 9280_02
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Cabin         8494 non-null   object
 3   Destination   8511 non-null   object
 4   Age           8514 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8512 non-null   float64
 7   FoodCourt     8510 non-null   float64
 8   ShoppingMall  8485 non-null   float64
 9   Spa           8510 non-null   float64
 10  VRDeck        8505 non-null   float64
 11  Name          8493 non-null   object
 12  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(6)
memory usage: 891.4+ KB

In [7]:
df_train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [8]:
def add_engineered_features(df):
    df = df.copy()
    
    df['AllSpentMoney'] = df['RoomService'] + df['FoodCourt'] + df['ShoppingMall'] + df['Spa'] + df['VRDeck']

    df['AllSpentMoneyToAge'] = df['AllSpentMoney'] / df['Age']
    
    return df

df_train = add_engineered_features(df_train)
df_test = add_engineered_features(df_test)

In [9]:
num_features = df_train.select_dtypes(include=['float64']).columns.tolist()
cat_features = df_train.select_dtypes(include=['object']).columns.tolist()

all_features = num_features + cat_features

print(f"cat: {cat_features}")
print(f"\nnum: {num_features}")

cat: ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP', 'Name']

num: ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'AllSpentMoney', 'AllSpentMoneyToAge']

In [10]:
numeric_data = df_train[num_features]
corr_matrix = numeric_data.corr().abs()

upper_triangle = corr_matrix.where(np.triu(np.ones(shape=corr_matrix.shape), k=1).astype(bool))

features_to_drop = [column for column in upper_triangle.columns if any(upper_triangle[column] > 0.9)]

print(f"Найдено {len(features_to_drop)} сильно скоррелированных признаков для удаления: {features_to_drop}")

for col in features_to_drop:
    if col in num_features:
        num_features.remove(col)
    if col in all_features:
        all_features.remove(col)

print(f"Осталось признаков для обучения: {len(all_features)}")

Найдено 1 сильно скоррелированных признаков для удаления: ['AllSpentMoneyToAge']
Осталось признаков для обучения: 13

In [11]:
correlations = numeric_data.corrwith(df_train['Transported'])
correlations

Age                  -0.075026
RoomService          -0.244611
FoodCourt             0.046566
ShoppingMall          0.010141
Spa                  -0.221131
VRDeck               -0.207075
AllSpentMoney        -0.197671
AllSpentMoneyToAge   -0.192714
dtype: float64

In [12]:
X = df_train[all_features]
y = df_train['Transported']

In [13]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="most_frequent")),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, num_features),
    ('cat', categorical_transformer, cat_features)
])

In [14]:
#models_to_compare = {
#    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
#    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
#    "HistGradientBoostingClassifier": HistGradientBoostingClassifier(random_state=42),
#    "BaggingClassifier": BaggingClassifier(random_state=42),
#    "AdaBoostClassifier": AdaBoostClassifier(random_state=42),
#
#    "XGBoost": XGBClassifier(n_estimators=100, random_state=42),
#    "LightGBM": LGBMClassifier(n_estimators=100, random_state=42),
#    "CatBoost": CatBoostClassifier(iterations=100, random_state=42, verbose=0)
#}
#
#results = []
#
#for name, model in models_to_compare.items():
#    try:
#        pipeline = Pipeline(steps=[
#            ('preprocessor', preprocessor),
#            ('model', model)
#        ])
#    
#        scores = cross_val_score(pipeline, X, y, cv=5, scoring='accuracy', n_jobs=-1)
#            
#        results.append({
#            'model': name,
#            'accuracy_score': scores.mean(),
#            'std_score': scores.std()
#        })
#    except Exception as e:
#        print(f"model: {model}, error: {e}")
#
#results_df = pd.DataFrame(results).sort_values(by='accuracy_score', ascending=False)

In [15]:
#results_df

In [16]:
import optuna
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import cross_val_score
import time

def objective(trial):
    start = time.time()
    
    params = {
        'max_iter': trial.suggest_int('max_iter', 100, 300),  
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 10, 50),
        'l2_regularization': trial.suggest_float('l2_regularization', 0, 1),
        'max_bins': trial.suggest_int('max_bins', 128, 255),
    }
    
    model = HistGradientBoostingClassifier(
        **params, 
        random_state=42,
        early_stopping=True,  
        validation_fraction=0.1
    )
    
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('model', model)
    ])
    
    scores = cross_val_score(
        pipeline, X, y, 
        cv=5,           
        scoring='accuracy', 
        n_jobs=1
    )
    
    print(f"Trial {trial.number}: accuracy={scores.mean():.4f}, time={time.time()-start:.1f}s")
    
    return scores.mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30, show_progress_bar=True)

print("\n✅ Лучшие параметры:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")
print(f"✅ Лучшая accuracy: {study.best_value:.4f}")

[I 2026-06-30 08:40:53,866] A new study created in memory with name: no-name-74156430-3d15-40d6-91a0-c4d24385772f

  0%|          | 0/30 [00:00<?, ?it/s]

Trial 0: accuracy=0.7931, time=614.1s
[I 2026-06-30 08:51:07,976] Trial 0 finished with value: 0.7930545510130751 and parameters: {'max_iter': 296, 'learning_rate': 0.016897663187722834, 'max_depth': 4, 'min_samples_leaf': 25, 'l2_regularization': 0.8422468023952399, 'max_bins': 212}. Best is trial 0 with value: 0.7930545510130751.
Trial 1: accuracy=0.7945, time=182.7s
[I 2026-06-30 08:54:10,695] Trial 1 finished with value: 0.7945495308005408 and parameters: {'max_iter': 162, 'learning_rate': 0.10813005081605609, 'max_depth': 3, 'min_samples_leaf': 24, 'l2_regularization': 0.002324602660148778, 'max_bins': 161}. Best is trial 1 with value: 0.7945495308005408.
Trial 2: accuracy=0.7962, time=529.8s
[I 2026-06-30 09:03:00,474] Trial 2 finished with value: 0.7961601147704029 and parameters: {'max_iter': 204, 'learning_rate': 0.025162157682640993, 'max_depth': 5, 'min_samples_leaf': 43, 'l2_regularization': 0.03339980875358439, 'max_bins': 217}. Best is trial 2 with value: 0.7961601147704029.
Trial 3: accuracy=0.7931, time=224.8s
[I 2026-06-30 09:06:45,289] Trial 3 finished with value: 0.7930540216292977 and parameters: {'max_iter': 105, 'learning_rate': 0.05869489100647225, 'max_depth': 4, 'min_samples_leaf': 38, 'l2_regularization': 0.664091453797081, 'max_bins': 180}. Best is trial 2 with value: 0.7961601147704029.
Trial 4: accuracy=0.7945, time=158.3s
[I 2026-06-30 09:09:23,620] Trial 4 finished with value: 0.7945490675897355 and parameters: {'max_iter': 196, 'learning_rate': 0.16572711523554573, 'max_depth': 5, 'min_samples_leaf': 19, 'l2_regularization': 0.30128337830074137, 'max_bins': 242}. Best is trial 2 with value: 0.7961601147704029.
Trial 5: accuracy=0.7941, time=704.2s
[I 2026-06-30 09:21:07,849] Trial 5 finished with value: 0.7940894301249808 and parameters: {'max_iter': 194, 'learning_rate': 0.016786334733613222, 'max_depth': 7, 'min_samples_leaf': 15, 'l2_regularization': 0.5033966781045718, 'max_bins': 171}. Best is trial 2 with value: 0.7961601147704029.
Trial 6: accuracy=0.7956, time=134.6s
[I 2026-06-30 09:23:22,450] Trial 6 finished with value: 0.7955846746043354 and parameters: {'max_iter': 164, 'learning_rate': 0.17539050279862725, 'max_depth': 7, 'min_samples_leaf': 30, 'l2_regularization': 0.30259844373880795, 'max_bins': 221}. Best is trial 2 with value: 0.7961601147704029.
Trial 7: accuracy=0.7943, time=444.0s
[I 2026-06-30 09:30:46,447] Trial 7 finished with value: 0.7943189179924973 and parameters: {'max_iter': 274, 'learning_rate': 0.042358110726783776, 'max_depth': 7, 'min_samples_leaf': 49, 'l2_regularization': 0.846051873133614, 'max_bins': 183}. Best is trial 2 with value: 0.7961601147704029.
Trial 8: accuracy=0.7927, time=409.3s
[I 2026-06-30 09:37:35,730] Trial 8 finished with value: 0.7927085987145238 and parameters: {'max_iter': 106, 'learning_rate': 0.017807791354361304, 'max_depth': 6, 'min_samples_leaf': 29, 'l2_regularization': 0.06903728670417042, 'max_bins': 208}. Best is trial 2 with value: 0.7961601147704029.
Trial 9: accuracy=0.7934, time=441.4s
[I 2026-06-30 09:44:57,160] Trial 9 finished with value: 0.7933986504684054 and parameters: {'max_iter': 144, 'learning_rate': 0.03388712660395941, 'max_depth': 6, 'min_samples_leaf': 19, 'l2_regularization': 0.827210331355336, 'max_bins': 166}. Best is trial 2 with value: 0.7961601147704029.
Trial 10: accuracy=0.7947, time=245.3s
[I 2026-06-30 09:49:02,491] Trial 10 finished with value: 0.7946642085613267 and parameters: {'max_iter': 253, 'learning_rate': 0.07347019391340771, 'max_depth': 8, 'min_samples_leaf': 50, 'l2_regularization': 0.20050712989273423, 'max_bins': 130}. Best is trial 2 with value: 0.7961601147704029.
Trial 11: accuracy=0.7926, time=131.4s
[I 2026-06-30 09:51:13,875] Trial 11 finished with value: 0.7925931930510439 and parameters: {'max_iter': 220, 'learning_rate': 0.25363339333005874, 'max_depth': 8, 'min_samples_leaf': 38, 'l2_regularization': 0.2730694147460898, 'max_bins': 243}. Best is trial 2 with value: 0.7961601147704029.
Trial 12: accuracy=0.7905, time=501.1s
[I 2026-06-30 09:59:35,025] Trial 12 finished with value: 0.7905235671731766 and parameters: {'max_iter': 158, 'learning_rate': 0.01021228680330806, 'max_depth': 5, 'min_samples_leaf': 37, 'l2_regularization': 0.43542374756140173, 'max_bins': 219}. Best is trial 2 with value: 0.7961601147704029.
Trial 13: accuracy=0.7929, time=119.7s
[I 2026-06-30 10:01:34,735] Trial 13 finished with value: 0.7929384174469012 and parameters: {'max_iter': 226, 'learning_rate': 0.2597851259764309, 'max_depth': 7, 'min_samples_leaf': 43, 'l2_regularization': 0.11731137199412317, 'max_bins': 233}. Best is trial 2 with value: 0.7961601147704029.
Trial 14: accuracy=0.7945, time=566.6s
[I 2026-06-30 10:11:01,332] Trial 14 finished with value: 0.7945488690708189 and parameters: {'max_iter': 186, 'learning_rate': 0.026395142331908667, 'max_depth': 6, 'min_samples_leaf': 32, 'l2_regularization': 0.41705290730361044, 'max_bins': 199}. Best is trial 2 with value: 0.7961601147704029.
Trial 15: accuracy=0.7947, time=237.0s
[I 2026-06-30 10:14:58,307] Trial 15 finished with value: 0.7946646055991599 and parameters: {'max_iter': 130, 'learning_rate': 0.08791747891439505, 'max_depth': 5, 'min_samples_leaf': 44, 'l2_regularization': 0.1711239412958629, 'max_bins': 255}. Best is trial 2 with value: 0.7961601147704029.
Trial 16: accuracy=0.7949, time=164.6s
[I 2026-06-30 10:17:42,887] Trial 16 finished with value: 0.7948940272937042 and parameters: {'max_iter': 220, 'learning_rate': 0.14811176818840682, 'max_depth': 4, 'min_samples_leaf': 10, 'l2_regularization': 0.6145949278923639, 'max_bins': 225}. Best is trial 2 with value: 0.7961601147704029.
Trial 17: accuracy=0.7958, time=598.9s
[I 2026-06-30 10:27:41,814] Trial 17 finished with value: 0.7958144271637403 and parameters: {'max_iter': 179, 'learning_rate': 0.02499839176975638, 'max_depth': 7, 'min_samples_leaf': 32, 'l2_regularization': 0.29889218227257947, 'max_bins': 200}. Best is trial 2 with value: 0.7961601147704029.
Trial 18: accuracy=0.7904, time=392.2s
[I 2026-06-30 10:34:14,064] Trial 18 finished with value: 0.7904076982988915 and parameters: {'max_iter': 244, 'learning_rate': 0.025303957055243294, 'max_depth': 3, 'min_samples_leaf': 43, 'l2_regularization': 0.008491105360875224, 'max_bins': 198}. Best is trial 2 with value: 0.7961601147704029.
Trial 19: accuracy=0.7944, time=412.7s
[I 2026-06-30 10:41:06,747] Trial 19 finished with value: 0.7944336619262555 and parameters: {'max_iter': 181, 'learning_rate': 0.04777381172349571, 'max_depth': 8, 'min_samples_leaf': 36, 'l2_regularization': 0.9722306731823047, 'max_bins': 148}. Best is trial 2 with value: 0.7961601147704029.
Trial 20: accuracy=0.7939, time=751.0s
[I 2026-06-30 10:53:37,724] Trial 20 finished with value: 0.793859015835854 and parameters: {'max_iter': 210, 'learning_rate': 0.011602100456065021, 'max_depth': 6, 'min_samples_leaf': 33, 'l2_regularization': 0.20465530564507137, 'max_bins': 194}. Best is trial 2 with value: 0.7961601147704029.
Trial 21: accuracy=0.7934, time=517.9s
[I 2026-06-30 11:02:15,582] Trial 21 finished with value: 0.7933987166413775 and parameters: {'max_iter': 171, 'learning_rate': 0.02959308362679341, 'max_depth': 7, 'min_samples_leaf': 27, 'l2_regularization': 0.32989387579024654, 'max_bins': 208}. Best is trial 2 with value: 0.7961601147704029.
Trial 22: accuracy=0.7940, time=561.9s
[I 2026-06-30 11:11:37,533] Trial 22 finished with value: 0.7939739582885287 and parameters: {'max_iter': 137, 'learning_rate': 0.020185961453227014, 'max_depth': 7, 'min_samples_leaf': 31, 'l2_regularization': 0.3831604557741668, 'max_bins': 228}. Best is trial 2 with value: 0.7961601147704029.
Trial 23: accuracy=0.7952, time=389.0s
[I 2026-06-30 11:18:06,539] Trial 23 finished with value: 0.7952395163814502 and parameters: {'max_iter': 156, 'learning_rate': 0.039673719908869136, 'max_depth': 5, 'min_samples_leaf': 21, 'l2_regularization': 0.5410303050242906, 'max_bins': 220}. Best is trial 2 with value: 0.7961601147704029.
Trial 24: accuracy=0.7940, time=316.6s
[I 2026-06-30 11:23:23,155] Trial 24 finished with value: 0.7939732965588069 and parameters: {'max_iter': 177, 'learning_rate': 0.060807995385980966, 'max_depth': 6, 'min_samples_leaf': 46, 'l2_regularization': 0.24376973006059932, 'max_bins': 184}. Best is trial 2 with value: 0.7961601147704029.
Trial 25: accuracy=0.7966, time=182.1s
[I 2026-06-30 11:26:25,253] Trial 25 finished with value: 0.7966200169270463 and parameters: {'max_iter': 205, 'learning_rate': 0.16116001846240863, 'max_depth': 8, 'min_samples_leaf': 40, 'l2_regularization': 0.0994529829833502, 'max_bins': 237}. Best is trial 25 with value: 0.7966200169270463.
Trial 26: accuracy=0.7950, time=991.2s
[I 2026-06-30 11:42:56,475] Trial 26 finished with value: 0.7950093006112396 and parameters: {'max_iter': 237, 'learning_rate': 0.013022408140102443, 'max_depth': 8, 'min_samples_leaf': 42, 'l2_regularization': 0.10803277408791138, 'max_bins': 241}. Best is trial 25 with value: 0.7966200169270463.
Trial 27: accuracy=0.7956, time=772.1s
[I 2026-06-30 11:55:48,547] Trial 27 finished with value: 0.795584608431363 and parameters: {'max_iter': 207, 'learning_rate': 0.022347386308439448, 'max_depth': 8, 'min_samples_leaf': 40, 'l2_regularization': 0.13247316430431755, 'max_bins': 255}. Best is trial 25 with value: 0.7966200169270463.
Trial 28: accuracy=0.7974, time=185.3s
[I 2026-06-30 11:58:53,899] Trial 28 finished with value: 0.7974257390362964 and parameters: {'max_iter': 254, 'learning_rate': 0.12229777533749973, 'max_depth': 8, 'min_samples_leaf': 34, 'l2_regularization': 0.05437678870983234, 'max_bins': 206}. Best is trial 28 with value: 0.7974257390362964.
Trial 29: accuracy=0.7942, time=175.5s
[I 2026-06-30 12:01:49,382] Trial 29 finished with value: 0.794204107885767 and parameters: {'max_iter': 294, 'learning_rate': 0.12511019863875938, 'max_depth': 4, 'min_samples_leaf': 35, 'l2_regularization': 0.07046079865924038, 'max_bins': 213}. Best is trial 28 with value: 0.7974257390362964.

✅ Лучшие параметры:
  max_iter: 254
  learning_rate: 0.12229777533749973
  max_depth: 8
  min_samples_leaf: 34
  l2_regularization: 0.05437678870983234
  max_bins: 206
✅ Лучшая accuracy: 0.7974

In [17]:
print(study.best_params)
print(f"Best accuracy: {study.best_value:.4f}")

optuna.visualization.plot_optimization_history(study)
optuna.visualization.plot_param_importances(study)

{'max_iter': 254, 'learning_rate': 0.12229777533749973, 'max_depth': 8, 'min_samples_leaf': 34, 'l2_regularization': 0.05437678870983234, 'max_bins': 206}
Best accuracy: 0.7974

In [18]:
best_model = HistGradientBoostingClassifier(**study.best_params, random_state=42)

final_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', best_model)
])

final_pipeline.fit(X, y)

test_predictions = final_pipeline.predict(df_test[all_features])

In [19]:
submission = pd.DataFrame({
    'PassengerId': df_test.index,  
    'Transported': test_predictions
})

submission.to_csv('submission.csv', index=False)